name: kgw
favicon: null
layout_spectrum: 0.54696
typography_spectrum: 0.5
title: Keep Grid Weird
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00fe4d'
    - '#1b13e3'
    - '#116beb'
    - '#b00009'
    - '#c95e54'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
